version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: vo2max_postgres
    restart: always
    environment:
      POSTGRES_DB: vo2max_dev
      POSTGRES_USER: vo2max_user
      POSTGRES_PASSWORD: vo2max_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
